title: "Numerow"
baseurl: "https://upstagebeats.com"
url: "https://upstagebeats.com"

permalink: "/:categories/:year/:month/:day/:title:output_ext"

# Build settings
theme: minima
plugins:
  - jekyll-feed
